name: glowsun
description: "GlowSun - Cilt Bakım Uygulaması"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  image_picker: ^1.0.4
  table_calendar: ^3.0.9
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.7.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  mobile_scanner: ^3.5.6
  camera: ^0.10.5+9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.jpg"
